import { OTP_LENGTH, PHONE_LENGTH } from "@/lib/constants/auth";
import { INDIAN_STATES, PINCODE_PATTERN } from "@/lib/constants/india";
import type { AddressFormData } from "@/types/checkout.types";
import type { UserProfile } from "@/components/account/types";

/**
 * Returns true if an email is a synthetic/internal dummy email generated by auth providers
 * (e.g. `<phone>@gemostone.auth`, `@phone.auth`, `@supabase.auth`, or anything ending with `.auth`).
 */
export function isSyntheticEmail(email?: string | null): boolean {
  if (!email) return false;
  const lower = email.trim().toLowerCase();
  return (
    lower.endsWith(".auth") ||
    lower.includes("@gemostone.auth") ||
    lower.includes("@phone.auth") ||
    lower.includes("@supabase.auth")
  );
}

/**
 * Returns true if a user profile exists and contains all required profile information:
 *  - Name (full_name non-empty)
 *  - Email (email_id non-empty, real user email, and valid format)
 *  - Mobile Number (phone non-empty and at least 10 digits)
 */
export function isProfileComplete(
  profile: UserProfile | Record<string, any> | null | undefined
): boolean {
  if (!profile) return false;

  // 1. Full Name: must be non-empty string
  const rawName =
    (profile as any).fullName ??
    (profile as any).full_name ??
    (profile as any).name ??
    "";
  const trimmedName = typeof rawName === "string" ? rawName.trim() : "";
  const hasName =
    trimmedName.length > 0 &&
    trimmedName.toLowerCase() !== "valued customer" &&
    !trimmedName.toLowerCase().startsWith("user ");

  // 2. Email: must be non-empty string, NOT synthetic auth email, and valid format
  const rawEmail =
    (profile as any).email ??
    (profile as any).email_id ??
    (profile as any).emailId ??
    "";
  const trimmedEmail = typeof rawEmail === "string" ? rawEmail.trim() : "";
  const hasEmail = Boolean(
    trimmedEmail &&
      !isSyntheticEmail(trimmedEmail) &&
      trimmedEmail.includes("@") &&
      isValidEmail(trimmedEmail)
  );

  // 3. Mobile Number: must have at least 10 digits
  const rawPhone =
    (profile as any).phone ??
    (profile as any).phone_number ??
    (profile as any).phoneNumber ??
    (profile as any).mobile ??
    (profile as any).mobile_no ??
    (profile as any).mobileNumber ??
    "";
  const cleanPhone = String(rawPhone || "").replace(/\D/g, "");
  const hasPhone = cleanPhone.length >= 10;

  return hasName && hasEmail && hasPhone;
}

/**
 * Returns true if `phone` is exactly 10 digits (digits only, no spaces, hyphens, country code).
 * Pure function — no side effects.
 */
export function isValidPhone(phone: string): boolean {
  return /^\d{10}$/.test(phone.trim());
}

/**
 * Returns true if every slot in the OTP array contains exactly one digit.
 * Pure function — no side effects.
 */
export function isValidOtp(otp: string[]): boolean {
  return (
    otp.length === OTP_LENGTH &&
    otp.every((digit) => /^\d$/.test(digit))
  );
}

/**
 * Returns true if `name` contains only letters and spaces (no numbers, symbols, or special characters).
 * Does not impose any character length limit.
 */
export function isValidFullName(name: string): boolean {
  const trimmed = name.trim();
  if (!trimmed) return false;
  return /^[\p{L}\s]+$/u.test(trimmed) && /\p{L}/u.test(trimmed);
}

/**
 * Validates email address syntax.
 * Rejects synthetic auth dummy emails (*.auth).
 * Optional field: empty or whitespace-only values are treated as valid.
 * When provided, verifies standard format without spaces or consecutive dots.
 */
export function isValidEmail(email?: string | null): boolean {
  if (!email) return true;
  const trimmed = email.trim();
  if (!trimmed) return true;

  if (isSyntheticEmail(trimmed)) {
    return false;
  }

  if (trimmed.includes("..") || /\s/.test(trimmed)) {
    return false;
  }

  return /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*\.[a-zA-Z]{2,}$/.test(
    trimmed
  );
}

/**
 * Returns true if `pincode` is exactly 6 digits.
 */
export function isValidPincode(pincode: string): boolean {
  return PINCODE_PATTERN.test(pincode.trim());
}

/**
 * Returns true if `state` matches one of the predefined states in `INDIAN_STATES`.
 */
export function isValidState(state: string): boolean {
  return (INDIAN_STATES as readonly string[]).includes(state.trim());
}

export type AddressFormErrors = Partial<Record<keyof AddressFormData, string>>;

/**
 * Centralized validator for AddressFormSheet.
 * Preserves existing empty-only behavior for Line 1 and City without adding new validation.
 */
export function validateAddressForm(form: AddressFormData): {
  isValid: boolean;
  errors: AddressFormErrors;
} {
  const errors: AddressFormErrors = {};

  // 1. Full Name: required, letters and spaces only, no numbers, no special characters
  const fullName = form.fullName?.trim() || "";
  if (!fullName) {
    errors.fullName = "Full Name is required";
  } else if (!isValidFullName(fullName)) {
    errors.fullName = "Enter a valid name";
  }

  // 2. Phone Number: required, exactly 10 digits
  const phone = form.phone?.trim() || "";
  if (!phone) {
    errors.phone = "Phone Number is required";
  } else if (!isValidPhone(phone)) {
    errors.phone = "Enter a valid 10-digit phone number";
  }

  // 3. Email: optional, must be valid email syntax if entered
  const email = form.email?.trim() || "";
  if (email && !isValidEmail(email)) {
    errors.email = "Enter a valid email address";
  }

  // 4. Pincode: required, exactly 6 digits
  const pincode = form.pincode ? form.pincode.trim() : "";
  if (!pincode) {
    errors.pincode = "Pincode is required";
  } else if (!isValidPincode(pincode)) {
    errors.pincode = "Enter a valid 6-digit pincode";
  }

  // 5. Line 1: preserve existing empty-only check
  if (!form.line1 || !form.line1.trim()) {
    errors.line1 = "House / Flat / Floor is required";
  }

  // 6. Line 2: optional, NO validation needed

  // 7. City: preserve existing empty-only check
  if (!form.city || !form.city.trim()) {
    errors.city = "City is required";
  }

  // 8. State: required and must belong to INDIAN_STATES
  const state = form.state?.trim() || "";
  if (!state) {
    errors.state = "State is required";
  } else if (!isValidState(state)) {
    errors.state = "Select a valid state";
  }

  return {
    isValid: Object.keys(errors).length === 0,
    errors,
  };
}
